from dotenv import find_dotenv, load_dotenv
from unittest.mock import Mock, patch
import pytest
import app as app
import ApiAccess as api


@pytest.fixture
def client():
    # Use our test integration config instead of the 'real' version
    file_path = find_dotenv('.env.test')
    load_dotenv(file_path, override=True)

    # Create the new app.
    test_app = app.create_app()
    # Use the app to create a test_client that can be used in our tests.
    with test_app.test_client() as client:
        yield client


@patch('requests.get')
def test_index_page(mock_get_requests, client):
    # Replace call to requests.get(url) with our own function
    mock_get_requests.side_effect = mock_get_cards
    response = client.get('/')


def mock_get_cards(url, params):
    if url == 'https://api.trello.com/1/lists/5f6f787bf9461c809f224d0d/cards/': # if url == f'https://api.trello.com/1/boards/{TEST_BOARD_ID}/lists':
        response = Mock()
        # sample_trello_lists_response should point to some test response data
        response.json.return_value = TODO_DATA # sample_trello_lists_response
        return response
    return None


def test_index_page(client):
    response = client.get('/')
    # assert response == 200
    # assert b"Mop Floor" in response.data
    


TODO_DATA = """[
    {
        "id": "5f74f1c15dcc9440240e61be",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-16T18:26:04.802Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f787bf9461c809f224d0d",
        "idMembersVoted": [],
        "idShort": 20,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Mop Floor",
        "pos": 221183,
        "shortLink": "pkJyRd9L",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/pkJyRd9L",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/pkJyRd9L/20-mop-floor",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "60033660b5c4225d259c2db3",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-16T18:54:24.217Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f787bf9461c809f224d0d",
        "idMembersVoted": [],
        "idShort": 59,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Wash Boards",
        "pos": 237567,
        "shortLink": "PTHI4st8",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/PTHI4st8",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/PTHI4st8/59-wash-boards",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "60034d1212e9cb8c92e90a2f",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-16T20:31:14.915Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f787bf9461c809f224d0d",
        "idMembersVoted": [],
        "idShort": 61,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Dust Bookcase",
        "pos": 253951,
        "shortLink": "qNpb3GZ6",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/qNpb3GZ6",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/qNpb3GZ6/61-dust-bookcase",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "600479827bd47c19197cb5ac",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-17T17:53:06.567Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f787bf9461c809f224d0d",
        "idMembersVoted": [],
        "idShort": 62,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Go to Supermarket",
        "pos": 270335,
        "shortLink": "j3a94bJd",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/j3a94bJd",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/j3a94bJd/62-go-to-supermarket",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    }
]"""

DOING_DATA = """
[
    {
        "id": "5f75aeb6c182544ae45eff17",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-17T19:25:58.997Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 23,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Water Plants",
        "pos": 599039,
        "shortLink": "4j67TPXr",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/4j67TPXr",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/4j67TPXr/23-water-plants",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f73a1cc97275d8230ef4b5a",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-17T19:30:55.410Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 8,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Clean Windows",
        "pos": 664575,
        "shortLink": "bnAhoDDu",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/bnAhoDDu",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/bnAhoDDu/8-clean-windows",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f6f78a49b076d461a84d854",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T17:36:26.759Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 3,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Clean Bathroom",
        "pos": 672767,
        "shortLink": "Dd4gcEAR",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/Dd4gcEAR",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/Dd4gcEAR/3-clean-bathroom",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f75b18e1894eb2ecb4d2869",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:15:37.326Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 26,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Hoover Stairs",
        "pos": 702975,
        "shortLink": "nKR4Lwtl",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/nKR4Lwtl",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/nKR4Lwtl/26-hoover-stairs",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f744efb647dfc8e2fde1ea7",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T18:22:37.629Z",
        "desc": "",
        "descData": null,
        "dueReminder": 1440,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 11,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Clean Bedroom",
        "pos": 703487,
        "shortLink": "ZzBJ7pJW",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": "2020-11-16T20:29:00.000Z",
            "dueComplete": true,
            "start": null
        },
        "dueComplete": true,
        "due": "2020-11-16T20:29:00.000Z",
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/ZzBJ7pJW",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/ZzBJ7pJW/11-clean-bedroom",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f744fcef1813717ae09261e",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:15:36.132Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 14,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Jetwash Bins",
        "pos": 703551,
        "shortLink": "ySDOYsYu",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/ySDOYsYu",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/ySDOYsYu/14-jetwash-bins",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f6f7897841c9f78e5b22d2a",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T18:22:44.507Z",
        "desc": "",
        "descData": null,
        "dueReminder": 1440,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 1,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Washing Up",
        "pos": 703615,
        "shortLink": "iTvxWZKF",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": "2020-11-12T20:29:00.000Z",
            "dueComplete": true,
            "start": null
        },
        "dueComplete": true,
        "due": "2020-11-12T20:29:00.000Z",
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/iTvxWZKF",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/iTvxWZKF/1-washing-up",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f744f4a8b0f4e856d4add7f",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:57.638Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 13,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Wash Dishes",
        "pos": 703999,
        "shortLink": "L4jTRr4E",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/L4jTRr4E",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/L4jTRr4E/13-wash-dishes",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f7213fbc6280b37d5c364b8",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:59.690Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 5,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Clean Oven",
        "pos": 704127,
        "shortLink": "MnZOZhkB",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/MnZOZhkB",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/MnZOZhkB/5-clean-oven",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f74523385b27a208e778a27",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:58.725Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 16,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Dust TV",
        "pos": 704255,
        "shortLink": "DRXcM7tw",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/DRXcM7tw",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/DRXcM7tw/16-dust-tv",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "6003432f01b6ef8e738a2b26",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:56.174Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 60,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Renew Passport",
        "pos": 704511,
        "shortLink": "dhOXsdB3",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/dhOXsdB3",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/dhOXsdB3/60-renew-passport",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f75b29b77f0f46af2853abb",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:50.242Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 27,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Put Bins Out",
        "pos": 705535,
        "shortLink": "jdfJKOoR",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/jdfJKOoR",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/jdfJKOoR/27-put-bins-out",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f75af098ecef32b9ec9c81f",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:53.500Z",
        "desc": "",
        "descData": null,
        "dueReminder": 1440,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 24,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Match up Socks",
        "pos": 709631,
        "shortLink": "wH7h6Kh0",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": "2020-11-26T20:29:00.000Z",
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": "2020-11-26T20:29:00.000Z",
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/wH7h6Kh0",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/wH7h6Kh0/24-match-up-socks",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f75b4776f74e58232f7ded0",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:04:48.510Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5fa80ea247eeb75b38c7259e",
        "idMembersVoted": [],
        "idShort": 29,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Sort DVD Collection",
        "pos": 713727,
        "shortLink": "ApiqdlLf",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/ApiqdlLf",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/ApiqdlLf/29-sort-dvd-collection",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    }
]"""

DONE_DATA = """[
    {
        "id": "5ff84a83cf43367e67ca4a82",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-14T15:05:28.845Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f7883333c1880d598e148",
        "idMembersVoted": [],
        "idShort": 56,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Paint Ceiling",
        "pos": 16384,
        "shortLink": "SBaeSgNw",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/SBaeSgNw",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/SBaeSgNw/56-paint-ceiling",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "60006112457f3d70d2afbbf8",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:17:25.449Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f7883333c1880d598e148",
        "idMembersVoted": [],
        "idShort": 58,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Sweep Yard",
        "pos": 795647,
        "shortLink": "b5qzT5tP",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/b5qzT5tP",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/b5qzT5tP/58-sweep-yard",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5ff88765219f44455a08fb3c",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T14:17:36.516Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f7883333c1880d598e148",
        "idMembersVoted": [],
        "idShort": 57,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Prune Bushes",
        "pos": 861183,
        "shortLink": "wvNPpmUD",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/wvNPpmUD",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/wvNPpmUD/57-prune-bushes",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5ff848ce6e08961821ddd8f7",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T17:36:58.954Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f7883333c1880d598e148",
        "idMembersVoted": [],
        "idShort": 55,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "wash floor",
        "pos": 926719,
        "shortLink": "dUGRegTL",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/dUGRegTL",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/dUGRegTL/55-wash-floor",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    },
    {
        "id": "5f75b3802907545c8bf537c9",
        "checkItemStates": null,
        "closed": false,
        "dateLastActivity": "2021-01-23T17:37:00.556Z",
        "desc": "",
        "descData": null,
        "dueReminder": null,
        "idBoard": "5f6f7855bd60681aba0d6abd",
        "idList": "5f6f7883333c1880d598e148",
        "idMembersVoted": [],
        "idShort": 28,
        "idAttachmentCover": null,
        "idLabels": [],
        "manualCoverAttachment": false,
        "name": "Unblock Sink",
        "pos": 992255,
        "shortLink": "CzSYtiEF",
        "isTemplate": false,
        "cardRole": null,
        "badges": {
            "attachmentsByType": {
                "trello": {
                    "board": 0,
                    "card": 0
                }
            },
            "location": false,
            "votes": 0,
            "viewingMemberVoted": false,
            "subscribed": false,
            "fogbugz": "",
            "checkItems": 0,
            "checkItemsChecked": 0,
            "checkItemsEarliestDue": null,
            "comments": 0,
            "attachments": 0,
            "description": false,
            "due": null,
            "dueComplete": false,
            "start": null
        },
        "dueComplete": false,
        "due": null,
        "idChecklists": [],
        "idMembers": [],
        "labels": [],
        "shortUrl": "https://trello.com/c/CzSYtiEF",
        "start": null,
        "subscribed": false,
        "url": "https://trello.com/c/CzSYtiEF/28-unblock-sink",
        "cover": {
            "idAttachment": null,
            "color": null,
            "idUploadedBackground": null,
            "size": "normal",
            "brightness": "light",
            "idPlugin": null
        }
    }
]"""
